### ISSUE TITLE
Reassign Technology Version doesn't work

### ISSUE THREAD

**Issue by gpimblott** [KainosSoftwareLtd/TechRadar#87] opened 2016-11-25 16:00 UTC
I added Pyton to a project, with no version.  I then added a new version to Python and tried to update the existing entry for the project - It didn't work :(

I eventually deleted Python from the project and readded with the correct version

**Comment by xjedam** [comment] 2016-11-28 09:24
Can't seem to reproduce the issue, could we have more details?

**Comment by xjedam** [comment] 2016-11-28 11:00
Closing for now - can't reproduce locally, on dev env or on prod.

**Closed as completed by xjedam** 2016-11-28 11:00 UTC
Labels: bug, High Priority
